### ISSUE TITLE
Create gh-pages branch for demo

### ISSUE THREAD

**Issue by DavidSpriggs** [Esri/dojo-theme-flat#1]
@yiweima Create a branch called gh-pages. This will allow you to have a live demo site at:
http://esri.github.io/dojo-theme-flat/TEST_PAGES
Then have a link in the readme for the demo site.

**Comment by yiweima** [comment]
Working on it :)

**Comment by steveoh** [comment]
+1

**Comment by steveoh** [comment]
bummer, no gh-pages still....
