### ISSUE TITLE
Wrong version of Common.css comitted

### ISSUE THREAD

**Issue by meterlongcat** [Esri/dojo-theme-flat#5]
There are two Common.css files as follows:

/CSS/dojo/Common.css
/CSS/dojo/form/Common.css

Under commit ef481aa the /CSS/dojo/form/Common.css file was also committed as /CSS/dojo/Common.css, overwriting what was previously there. Both files now contain identical content, which is incorrect. 

This means that all /CSS/dojo/Common.css styles have been lost. This can be verified by performing DnD on a dijit.Tree. With the current version of /CSS/dojo/Common.css there is no success/fail icon on the DnD avatar. Rolling back to the previous version does show one.

Can this please be corrected.

**Comment by yiweima** [comment]
Hi, thanks for pointing this issue! This has been resolved.
